# Generated by Django 4.0.6 on 2022-08-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cashflowuploadfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
